services:
  db:
    container_name: postgres-lol #hostname
    image: postgres #nombre de la bd
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tubarao #postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=Lol
    
#el volumen se le pone ./ para decir que asi se llamara la carpeta y se
#almacene ahi mismo los datos esto evita agregar nuevamente el volumen

  pdAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=tubarao@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - pgadmin:/var/lib/pgadmin
      - pgadmin:/certs/server.cert
      - pgadmin:/certs/server.key
      - pgadmin:/pgadmin4/servers.json
    
volumes:
  postgres-data:
  pgadmin:

    
  # cloudbeaver:
  #   depends_on: #depende del servicio db
  #     - db
  #   image: dbeaver/cloudbeaver:latest
  #   ports:
  #     - 8978:8978
  #   volumes:
  #     - cloudbeaver-data:/var/cloudbeaver/workspace

# INSERT INTO "CHAMPIONS" ("CHAMPS_ID", "CHAMPS_NAME", "CHAMPS_HEALTH", "CHAMPS_AD", "CHAMPS_AP", "CHAMPS_MP", "CHAMPS_MANA")
# VALUES 
# (1, 'Ashe', 600, 75, 0, 300, 250),